"""Default configuration for the IBEX analysis pipeline."""

DEFAULT_BENCHMARK = "^IBEX"

DEFAULT_SYMBOLS = [
    "ANA.MC",
    "ACX.MC",
    "ACS.MC",
    "AENA.MC",
    "AMS.MC",
    "MTS.MC",
    "SAB.MC",
    "SAN.MC",
    "BKIA.MC",
    "BKT.MC",
    "BBVA.MC",
    "CABK.MC",
    "CLNX.MC",
    "CIE.MC",
    "ENG.MC",
    "ENC.MC",
    "ELE.MC",
    "FER.MC",
    "GRF.MC",
    "IAG.MC",
    "IBE.MC",
    "ITX.MC",
    "IDR.MC",
    "COL.MC",
    "MAP.MC",
    "TL5.MC",
    "MEL.MC",
    "MRL.MC",
    "NTGY.MC",
    "REE.MC",
    "REP.MC",
    "SGRE.MC",
    "TRE.MC",
    "TEF.MC",
    "VIS.MC",
]
